config/routes.rb
Rails.application.routes.draw do

  resources :todos do 
    collection do 
      get :check_off
    end
  end

  controller :jinn do 
    get 'jinn' => :index
    get 'jinn/predict'
  end

  resources :saved_blogposts do
    collection do 
      get :more
    end
  end

  devise_for :users, controllers: { sessions: 'users/sessions' }
  
  resources :blogposts do  
    collection do 
      get :more
    end
  end
  root to: "blogposts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/blogpost.rb
class Blogpost < ApplicationRecord
  include RelationsHelper

  validates :title, :body, presence: true
  validates :title, uniqueness: true

  has_many :saved_blogposts, dependent: :destroy
  belongs_to :user

  # Returns saved_blogpost, if exists
  def saved_by?(some_user)
    saved_blogposts.find_by(user_id: some_user.id)
  end

  # Returns [blogposts, has_more]
  def self.get_blogposts(limit, user: nil)
    blogposts =
      if user
        self.where(user_id: user.id).limit(limit + 1).
          order(:created_at).reverse_order
      else
        self.limit(limit + 1).order(:created_at).reverse_order
      end

    if blogposts.count > limit
      [blogposts.limit(limit), true]
    else
      [blogposts, false]
    end
  end

  # Determine the quantity of blogposts already displayed when requesting more
  def self.blogposts_displayed(blogposts_per_request, more_counter: 1)
    more_counter.to_i * blogposts_per_request
  end

  # Determine the max limit for total blogposts to be shown after this request
  def self.limit_blogposts(blogposts_per_request, more_counter: 0)
    (1 + more_counter.to_i) * blogposts_per_request
  end
end

app/controllers/blogposts_controller.rb
class BlogpostsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :more, :show]

  # GET /blogposts
  # GET /blogposts.json
  def index
    # Limiting content
    limit = Blogpost.limit_blogposts(BLOGPOSTS_PER_REQUEST)

    # Requesting user-specific posts
    if params[:user_id]
      @user = User.find(params[:user_id])
      @blogposts, @has_more = Blogpost.get_blogposts(limit, user: @user)
    # Requesting 'My posts' is marked with :not_authenticated
    # when the user is not signed in
    elsif params[:must_authenticate]
      authenticate_user!
      redirect_to blogposts_path(user: current_user) and return
    # Requesting unfiltered posts
    else
      @blogposts, @has_more = Blogpost.get_blogposts(limit, user: nil)
    end
  end

  # GET /blogposts/more
  # Renders additional blogposts if user requests more content
  def more
    limit = Blogpost.limit_blogposts(BLOGPOSTS_PER_REQUEST, more_counter: params[:more])

    # Requesting more user-specific posts
    if params[:user_id]
      @user = User.find(params[:user_id])
      blogposts, @has_more = Blogpost.get_blogposts(limit, user: @user)
    # Requesting more unfiltered posts
    else
      blogposts, @has_more = Blogpost.get_blogposts(limit, user: nil)
    end

    blogposts_displayed =
      Blogpost.blogposts_displayed(BLOGPOSTS_PER_REQUEST, more_counter: params[:more])
    @blogposts_to_render = blogposts[blogposts_displayed..-1]

    respond_to do |format|
      format.js { render partial: 'shared/blogposts/more_blogposts.js.erb' }
    end
  end

  # GET /blogposts/1
  # GET /blogposts/1.json
  def show
    @blogpost = get_blogpost
    @full_length = true
  end

  # GET /blogposts/new
  def new
    @blogpost = Blogpost.new
  end

  # GET /blogposts/1/edit
  def edit
    @blogpost = get_blogpost(user: current_user)
  end

  # POST /blogposts
  # POST /blogposts.json
  def create
    @blogpost = current_user.blogposts.build(blogpost_params)

    respond_to do |format|
      if @blogpost.save
        format.html do
          redirect_to @blogpost, notice: 'Blogpost was successfully created.'
        end
        format.json { render :show, status: :created, location: @blogpost }
      else
        format.html { render :new }
        format.json do
          render json: @blogpost.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # PATCH/PUT /blogposts/1
  # PATCH/PUT /blogposts/1.json
  def update
    @blogpost = get_blogpost(user: current_user)

    respond_to do |format|
      if @blogpost.update(blogpost_params)
        format.html do
          redirect_to @blogpost, notice: 'Blogpost was successfully updated.'
        end
        format.json { render :show, status: :ok, location: @blogpost }

        @updated_blogpost = @blogpost
        ActionCable.server.broadcast(
          'blogposts',
          blogpost: @blogpost,
          html: render_to_string(
            partial: 'shared/blogposts/blogpost',
            object: @blogpost,
            layout: false
          )
        )
      else
        format.html { render :edit }
        format.json do
          render json: @blogpost.errors, status: :unprocessable_entity
        end
      end
    end
  end

  # DELETE /blogposts/1
  # DELETE /blogposts/1.json
  def destroy
    blogpost = get_blogpost(user: current_user)
    blogpost.destroy!

    respond_to do |format|
      format.html do
        redirect_back(
          fallback_location: root_path,
          notice: 'Blogpost was successfully deleted.'
        )
      end
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def get_blogpost(user: nil)
      if user && current_user.is_master_admin?
        Blogpost.find(params[:id])
      elsif user
        user.blogposts.find(params[:id])
      else
        Blogpost.find(params[:id])
      end
    end

    # Only allow a list of trusted parameters through.
    def blogpost_params
      params.require(:blogpost).permit(:title, :body)
    end
end

app/helpers/blogposts_helper.rb
module BlogpostsHelper
  def format_time(time)
    now = Time.now
    diff = (now - time)/60/60/24/4  # in units of 4 days

    # more than 4 days
    if diff >= 1
      return time.strftime("%-d %b %Y")   # ex: '3 Sep 2020'
    end

    # 24 hours to just under 4 days
    diff *= 4   # in units of single days
    if diff >= 1
      return diff.round.to_s + "d"      # ex: 3d
    end

    # 1 hour to just under 24 hours
    diff *= 24  # in units of single hours
    if diff >= 1
      return diff.round.to_s + "h"      # ex: '23h'
    end

    # 1 min to 1 hour
    diff *= 60  # in units of single minutes
    if diff >= 1
      return diff.round.to_s + "min"    # ex: '59min'
    end

    # less than 1 min
    diff *= 60  # in units of single seconds
    diff.round.to_s + "sec"               # ex: '59sec'
  end
end

app/views/shared/blogposts/_blogpost.html.erb
<% if @full_length %>
  <div class="card mx-auto col-xl-8 col-lg-10 col-md-12 col-sm-12 col-12 p-0">
<% else %>
  <div class="card mx-auto col-xl-8 col-lg-9 col-md-11 col-sm-11 col-12 p-0">
<% end %>
  <% if blogpost == @updated_blogpost %>
    <div class="blogpost-highlight">
  <% else %>
    <div>
  <% end %>
    <div class="card-body">

      <div class="card-signature">
        <%= link_to blogposts_path(user_id: blogpost.user_id) do %>
          <div class="d-inline-block align-middle">
            <% if blogpost.user.avatar.attached? %>
              <%= image_tag(blogpost.user.avatar, size: "40x40", class: "rounded-circle") %>
            <% else %>
              <%= image_tag('blank_avatar.jpg', size: "40x40", class: "rounded-circle") %>
            <% end %>
          </div>
          <div class="d-inline-block align-middle card-signature-info">
            <h6 class="card-signature-author"><%= "#{blogpost.user.first_name} #{blogpost.user.last_name}" %></h6>
            <p class="card-signature-time"><small><%= format_time(blogpost.created_at) %></small></p>
          </div>
        <% end %>
      </div>

      <% if @full_length %>
        <h4 class="card-title text-center"><%= blogpost.title %></h4>
        <p class="card-text">
          <%= simple_format(blogpost.body) %>
        </p>
      <% else %>
        <%= link_to blogpost, class: "blogpost-title-link" do %>
          <h5 class="card-title"><%= blogpost.title %></h5>
        <% end %>

        <%= link_to blogpost, class: "blogpost-body-link" do %>
          <p class="card-text">
            <%= simple_format(truncate((blogpost.body), length: 370)) %>
          </p>
        <% end %>
      <% end %>

      <% if local_assigns.has_key?(:saved_blogpost) %>
        <%= render partial: '/shared/blogposts/blogpost_actions', locals: { blogpost: blogpost, saved_blogpost: saved_blogpost } %>
      <% else %>
        <%= render partial: '/shared/blogposts/blogpost_actions', locals: { blogpost: blogpost } %>
      <% end %>

    </div>
  </div>
</div>

app/views/shared/blogposts/_blogpost_actions.html.erb
<div class="blogpost-actions d-flex justify-content-between">

	<% if local_assigns.key? :saved_blogpost %>
	  <div class="blogpost-view-actions">
	    <a><%= link_to '', saved_blogpost, method: :delete, class: "fas fa-bookmark", title: "unsave_blogpost" %></a>
	  </div>
  <% elsif user_signed_in? && blogpost.saved_by?(current_user) %>
    <div class="blogpost-view-actions">
      <a><%= link_to '', current_user.saved_blogposts.find_by(blogpost_id: blogpost.id), method: :delete, class: "fas fa-bookmark", title: "unsave_blogpost" %></a>
    </div>
	<% elsif !user_signed_in? %>
	  <div>
      <a><%= link_to '', saved_blogposts_path(blogpost_id: blogpost), method: :post, class: "far fa-bookmark", title: "save_blogpost"  %></a>
    </div>
  <% else %>
    <div>
      <a><%= link_to '', saved_blogposts_path(blogpost_id: blogpost), method: :post, class: "far fa-bookmark", title: "save_blogpost" %></a>
    </div>
	<% end %>

  <div>
    <% if user_signed_in? && (blogpost.created_by?(current_user) || current_user.is_master_admin?) %>
      <a><%= link_to 'Edit', edit_blogpost_path(blogpost), class: "btn btn-outline-info btn-sm btn-no-outline" %></a>
      <a><%= link_to 'Delete', blogpost, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm btn-no-outline" %></a>
    <% end %>
  </div>

</div>

app/views/shared/blogposts/_more_blogposts.html.erb
<% if @blogposts_to_render && @blogposts_to_render.count > 0 %>
	<% @blogposts_to_render.each do |blogpost| %>
  	<%= render partial: 'shared/blogposts/blogpost', object: blogpost %>
  <% end %>
<% elsif @saved_blogposts_to_render.count > 0 %>
	<% @saved_blogposts_to_render.each do |saved_blogpost| %>
		<%= render partial: 'shared/blogposts/blogpost', object: saved_blogpost.blogpost, locals: { saved_blogpost: saved_blogpost } %>
	<% end %>
<% end %>

app/views/shared/blogposts/_more_blogposts.js.erb
moreContentDiv = document.getElementById("more-content")
moreButtonDiv = document.getElementById("more-button")

moreBlogposts = "<%= j render partial: 'shared/blogposts/more_blogposts.html.erb' %>"
updatedButton = "<%= j render partial: 'shared/blogposts/more_button.html.erb' %>"

moreContentDiv.insertAdjacentHTML("beforeend", moreBlogposts)
moreButtonDiv.innerHTML = updatedButton

app/views/shared/blogposts/_more_button.html.erb
<% if @has_more %>
	<% if controller_name == 'blogposts' %>
  	<%= link_to 'More...', more_blogposts_path(more: (params[:more].to_i + 1), user_id: (@user ? @user.id : nil)), class: "btn btn-outline-secondary btn-sm btn-more", id: "more-button", remote: true %>  
	<% elsif controller_name == 'saved_blogposts' %>
		<%= link_to 'More...', more_saved_blogposts_path(more: (params[:more].to_i + 1)), class: "btn btn-outline-secondary btn-sm btn-more", id: "more-button", remote: true %> 
	<% end %>
<% end %>