config/routes.rb
Rails.application.routes.draw do

  resources :todos do 
    collection do 
      get :check_off
    end
  end

  controller :jinn do 
    get 'jinn' => :index
    get 'jinn/predict'
  end

  resources :saved_blogposts do
    collection do 
      get :more
    end
  end

  devise_for :users, controllers: { sessions: 'users/sessions' }
  
  resources :blogposts do  
    collection do 
      get :more
    end
  end
  root to: "blogposts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/todo.rb
class Todo < ApplicationRecord
  include RelationsHelper

  enum status: {
    completed: 1,
    not_completed: 0
  }

  validates :user_id, presence: true

  belongs_to :user
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  # GET /todos
  # GET /todos.json
  def index
    @todos = current_user.todos
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/check
  def check_off
    todo = get_todo(user: current_user)
    todo.status =
        todo.status == "not_completed" ? "completed" : "not_completed"
    todo.save!

    redirect_back fallback_location: root_path
  end

  # GET /todos/1/edit
  def edit
    @todo = get_todo(user: current_user)
  end

  # POST /todos
  # POST /todos.json
  def create
    todo = current_user.todos.build(todo_params)

    respond_to do |format|
      if todo.save
        format.html { redirect_to todos_path }
        format.json { render :show, status: :created, location: todo }
      else
        format.html { render :new }
        format.json { render json: todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1
  # PATCH/PUT /todos/1.json
  def update
    todo = get_todo(user: current_user)

    respond_to do |format|
      if todo.update(todo_params)
        format.html { redirect_back fallback_location: root_path }
        format.json { render :show, status: :ok, location: todo }
      else
        format.html { render :edit }
        format.json { render json: todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1
  # DELETE /todos/1.json
  def destroy
    todo = get_todo(user: current_user)

    todo.destroy
    respond_to do |format|
      format.html { redirect_back fallback_location: root_path }
      format.json { head :no_content }
    end
  end

  private

    def get_todo(user: current_user)
      user.todos.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:task, :status)
    end
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/shared/todos/_todo.html.erb
<tr class="d-flex">
  <% if todo.status == "completed" %>
    <td class="status-col col-1 text-center">
      <%= link_to check_off_todos_path(id: todo.id) do %>
        <span class="far fa-lg fa-check-square completed-icon"></span>
      <% end %>
    </td>
    <td class="col-8 completed-text"><%= todo.task %></td>
    <td class="col-3">
      <%= link_to 'Remove', todo, method: :delete, class: "btn btn-outline-danger btn-sm btn-no-outline float-right" %>
      <%= link_to 'Edit', edit_todo_path(todo), class: "btn btn-outline-info btn-sm btn-no-outline float-right" %>
    </td>
  <% else %>
    <td class="status-col col-1 text-center">
      <%= link_to check_off_todos_path(id: todo.id) do %>
        <span class="far fa-lg fa-square"></span>
      <% end %>
    </td>
    <td class="col-8"><%= todo.task %></td>
    <td class="col-3">
      <%= link_to 'Remove', todo, method: :delete, class: "btn btn-outline-danger btn-sm btn-no-outline float-right" %>
      <%= link_to 'Edit', edit_todo_path(todo), class: "btn btn-outline-info btn-sm btn-no-outline float-right" %>
    </td>
  <% end %>
</tr>