config/routes.rb
Rails.application.routes.draw do

  resources :todos do 
    collection do 
      get :check_off
    end
  end

  controller :jinn do 
    get 'jinn' => :index
    get 'jinn/predict'
  end

  resources :saved_blogposts do
    collection do 
      get :more
    end
  end

  devise_for :users, controllers: { sessions: 'users/sessions' }
  
  resources :blogposts do  
    collection do 
      get :more
    end
  end
  root to: "blogposts#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_mysidebar_left.html.erb
<% if user_signed_in? %>
  <% user_self_hash = { user_id: current_user.id } %>
<% else %>
  <% user_self_hash = { must_authenticate: true } %>
<% end %>

<div class="px-2">
  <% if user_signed_in?%>
    <% if current_user.avatar.attached? %>
      <%= link_to image_tag(current_user.avatar, class: "rounded-circle mx-auto mx-1 my-lg-2 my-md-2 my-sm-1 my-1 px-0 avatar img-fluid img-responsive border"), blogposts_path(user_self_hash) %>
    <% else %>
      <%= link_to image_tag('blank_avatar.jpg', class: "rounded-circle d-block mx-auto mx-1 my-lg-2 my-md-2 my-sm-1 my-1 px-0 avatar img-fluid img-responsive border"), blogposts_path(user_self_hash) %>
    <% end %>
  <% else %>
    <%= link_to image_tag('anonymous_avatar.jpg', class: "rounded-circle d-block mx-auto mx-1 my-lg-2 my-md-2 my-sm-1 my-1 px-0 avatar img-fluid img-responsive border"), blogposts_path %>
  <% end %>
</div>

<div class="sidebar-header px-xl-2">
  <h2><%= truncate(current_user && current_user.first_name, length: 15) %></h2>
  <h2><%= truncate(current_user && current_user.last_name, length: 15) %></h2>
</div>
<div class="list-group list-group-flush">
  <%= link_to "All posts", blogposts_path, class: "list-group-item list-group-item-action" %>
  <%= link_to "My posts", blogposts_path(user_self_hash), class: "list-group-item list-group-item-action" %>
  <%= link_to "Saved", saved_blogposts_path, class: "list-group-item list-group-item-action" %>
	<%= link_to "To-Do", todos_path, class: "list-group-item list-group-item-action" %>
	<%= link_to "Dilemma", jinn_path, class: "list-group-item list-group-item-action" %>
  <%= link_to "New", new_blogpost_path, class: "list-group-item list-group-item-action" %>
</div>

app/views/layouts/_navbar_top.html.erb
<nav class="navbar navbar-expand-md navbar-dark pl-lg-4 pl-md-2 pl-sm-1 pl-0 bg-dark topbar">

<%= link_to image_tag('mozport_icon_hq.png', class: "mozport_icon") + raw('<span class="navbar-brand ml-lg-2 ml-md-1 ml-sm-1 ml-1">MozPort</span>'), blogposts_path %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample04" aria-controls="navbarsExample04" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarsExample04">
    <ul class="navbar-nav mr-auto">
    </ul>
    <ul class="navbar-nav">
      <% if Blogpost.all.any? %>
        <%= link_to "About", Blogpost.find_by(id: 3), class: "nav-item pull-right active nav-link" %>
      <% else %>
        <%= link_to "About", blogposts_path, class: "nav-item pull-right active nav-link" %>
      <% end %>
      <% if !user_signed_in? %>
        <%= link_to "Register", new_user_registration_path, class: "nav-item pull-right active nav-link" %>
        <%= link_to "Login", new_user_session_path, class: "nav-item pull-right active nav-link" %>
      <% else %>
        <%= link_to "My account", edit_user_registration_path, class: "nav-item pull-right active nav-link" %>
        <%= link_to "Sign out", destroy_user_session_path, :method => :delete, class: "nav-item pull-right active nav-link" %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Bootstrap's responsive viewport meta tag -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://kit.fontawesome.com/534eee6254.js" crossorigin="anonymous"></script>

    <%= favicon_link_tag 'mozport_icon.ico' %>
    <title><%= yield :page_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid content-all">
      <div class="row row-top">
        <%= render(partial: '/layouts/navbar_top') %>
      </div>
      <div class="row row-main">
        <div class="col-xl-2 col-lg-2 col-md-2 col-sm-3 col-3 mysidebar-left bg-light">
          <%= render_if(render_left_bar?, partial: '/layouts/mysidebar_left') %>
        </div>

        <div class="col-xl-10 col-lg-10 col-md-10 col-sm-9 col-9 content-center">
          <%= display_alert %>
          <%= display_notice %>
          <header class="page-header">
            <h1><%= yield :page_title %></h1>
          </header>
          <main class='<%= controller.controller_name %>'>
            <%= yield %>
          </main>
        </div>
      </div>
    </div>

    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>